<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import DatePicker from '../components/DatePicker.vue'
import { categories } from '../data/categories'
import type { ReportSummary } from '../domain/types'
import { gateway } from '../gateway'
import { useAppStore } from '../stores/app'

const app = useAppStore(); const today = new Date(); const first = new Date(today.getFullYear(), today.getMonth(), 1)
const iso = (date: Date) => date.toISOString().slice(0, 10)
const filter = reactive({ from: iso(first), to: iso(today), employeeId: undefined as number | undefined, category: '' })
const summary = ref<ReportSummary | null>(null); const loading = ref(false); const message = ref('')
const desktopAvailable = Boolean(window.desktop)
async function generate() { loading.value = true; message.value = ''; try { summary.value = await gateway.reportSummary(filter) } catch (cause) { message.value = cause instanceof Error ? cause.message : 'Kunne ikke lage rapport.' } finally { loading.value = false } }
async function exportExcel() { try { const blob = await gateway.exportReport(filter); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `telefonhjelp-${filter.from}-${filter.to}.xlsx`; link.click(); URL.revokeObjectURL(url) } catch (cause) { message.value = cause instanceof Error ? cause.message : 'Kunne ikke eksportere.' } }
async function backup() { try { const path = window.desktop?.chooseBackupPath(); if (window.desktop && !path) return; message.value = await gateway.backup(path) } catch (cause) { message.value = cause instanceof Error ? cause.message : 'Kunne ikke sikkerhetskopiere.' } }
async function restore() { try { const path = window.desktop?.chooseRestorePath(); if (!path || !window.confirm('Gjenoppretting erstatter alle vanlige data og sletter midlertidig informasjon. Fortsette?')) return; const result = await gateway.restore(path); message.value = result.restarting ? 'Gjenoppretter data og starter programmet på nytt …' : result.message } catch (cause) { message.value = cause instanceof Error ? cause.message : 'Kunne ikke gjenopprette sikkerhetskopien.' } }
onMounted(generate)
</script>
<template><section class="workspace-header"><div><p class="eyebrow">Innsikt</p><h1>Rapporter</h1><p>Se aktivitet og behandlingstid uten kundeopplysninger.</p></div><div class="button-row"><button class="button button--ghost" @click="backup">Sikkerhetskopier data</button><button v-if="desktopAvailable" class="button button--ghost" @click="restore">Gjenopprett</button></div></section><section class="card report-filter"><DatePicker v-model="filter.from" label="Fra" :max="filter.to" /><DatePicker v-model="filter.to" label="Til" :min="filter.from" /><label>Ansatt<select v-model="filter.employeeId"><option :value="undefined">Alle</option><option v-for="employee in app.employees" :key="employee.id" :value="employee.id">{{ employee.name }}</option></select></label><label>Kategori<select v-model="filter.category"><option value="">Alle</option><option v-for="category in categories" :key="category">{{ category }}</option></select></label><button class="button button--primary" :disabled="loading" @click="generate">{{ loading ? 'Beregner…' : 'Vis rapport' }}</button></section><div v-if="message" class="alert alert--info">{{ message }}</div><section v-if="summary" class="metric-grid"><article><small>Opprettet</small><strong>{{ summary.created }}</strong></article><article><small>Lukket</small><strong>{{ summary.closed }}</strong></article><article><small>Åpne</small><strong>{{ summary.open }}</strong></article><article><small>Gj.snitt</small><strong>{{ summary.averageMinutes }} min</strong></article><article><small>Innen 30 min</small><strong>{{ summary.within30Percent }} %</strong></article><article><small>Innen 60 min</small><strong>{{ summary.within60Percent }} %</strong></article><article><small>Over 60 min</small><strong>{{ summary.over60Percent }} %</strong></article><article><small>Haster / eskalert</small><strong>{{ summary.urgent }} / {{ summary.escalated }}</strong></article></section><div class="report-actions"><button class="button button--dark button--large" :disabled="!summary" @click="exportExcel">Generer Excel-rapport</button><small>Navn, telefonnumre, beskrivelser, kommentarer og midlertidig informasjon tas aldri med.</small></div></template>
